### ISSUE TITLE
Enemy list in data file

### ISSUE THREAD

**Issue by lumbar527** [lumbar527/Dungeons-of-Kathallion#22]
**Is your feature request related to a problem? Please describe.**
There is no way for plugin authors to add enemies.

**Describe the solution you'd like**
I would like a special data file to define which series an enemy is in.
<details><summary>Idea</summary>
<p>

```
generic:
  - Orc
  - Goblin
  - Orc Archer
  - Warg
  - Cavern Troll
```

</p>
</details> 

**Describe alternatives you've considered**
The information could be defined with the enemy definition.

**Additional context**
N/A

**Comment by OcelotWalrus** [comment]
I'll make a PR about that and #23 .

**Comment by OcelotWalrus** [comment]
By the way it's generic and not general.
